import './globals.css';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Kanit, Roboto } from 'next/font/google';
import { EventProvider } from '@/hooks/EventProvider/EventProvider';

const kanit = Kanit({
    subsets: ['thai'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <EventProvider>
                <body className={`${kanit.className} ${roboto.className} antialiased`}>
                    <AntdRegistry>{children}</AntdRegistry>
                </body>
            </EventProvider>
        </html>
    );
}
